---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yaml
data:
  bootstrap.yaml: |-
    members_keys_dir: "/var/data/bootstrap/configs/"
    discovery_keys_dir: "/var/data/bootstrap/discovery-keys/"
    certificates_out_dir: "/var/data/bootstrap/certs/"
    certificate_name_offset_from_zero: True
    keys_name_format: "node-%d.json"
    discovery_nodes:
      -
        host: "something-0.somenet.somenamespace:13831"
        role: "some_material"
        cert_name: "something-0.json"
      -
        host: "something-1.somenet.somenamespace:13831"
        role: "some_material"
        cert_name: "something-1.json"
